chore: include near-abi-client examples
near/near-workspaces-rs pull request #303
Opened 2023-09-14 11:51 UTC by shariffdev

This PR includes the [near-abi-client](https://github.com/near/near-abi-client-rs?tab=readme-ov-file) examples.

2023-09-25 18:19 UTC, shariffdev commented
@frol This is ready to be reviewed

2024-01-27 17:41 UTC, frol requested changes

2024-01-27 17:41 UTC, frol commented on workspaces/Cargo.toml
> +near-abi-client = { git = "https://github.com/shariffdev/near-abi-client-rs", branch = "chore/bump-workspaces" }
near-abi-client 0.1.1 is now released, let's update: https://github.com/near/near-abi-client-rs/releases/tag/near-abi-client-v0.1.1

2024-01-30 10:47 UTC, shariffdev commented on examples/src/gen/adder.rs
I missed that while testing, will rm

2024-02-03 22:42 UTC, frol approved these changes

2024-02-03 22:49 UTC, merged